#
#Fri Apr 10 09:43:28 COT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[start-maximized, test-type, no-sandbox, lang\=es, disable-popup-blocking, disable-download-notification, ignore-certificate-errors, allow-running-insecure-content, disable-translate, always-authorize-plugins, disable-extensions, start-maximized, test-type, no-sandbox, lang\=es, disable-popup-blocking, disable-download-notification, ignore-certificate-errors, allow-running-insecure-content, disable-translate, always-authorize-plugins, disable-extensions, remote-allow-origins\=*], extensions\=[]}
